// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// process_chromosomes_threaded_cpp
Rcpp::List process_chromosomes_threaded_cpp(Rcpp::List per_chrom, int max_threads);
RcppExport SEXP _RNAPeaks_process_chromosomes_threaded_cpp(SEXP per_chromSEXP, SEXP max_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type per_chrom(per_chromSEXP);
    Rcpp::traits::input_parameter< int >::type max_threads(max_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(process_chromosomes_threaded_cpp(per_chrom, max_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RNAPeaks_process_chromosomes_threaded_cpp", (DL_FUNC) &_RNAPeaks_process_chromosomes_threaded_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RNAPeaks(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
