# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

process_chromosomes_threaded_cpp <- function(per_chrom, max_threads) {
    .Call(`_RNAPeaks_process_chromosomes_threaded_cpp`, per_chrom, max_threads)
}

