# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

process_chromosome_cpp <- function(anno_line_id, anno_transcript, anno_region, anno_start, anno_end, anno_strand, anno_gene, gene_name, gene_start, gene_end, peak_start, peak_end, peak_FC, peak_range, peak_transcripts, seed) {
    .Call(`_RNAPeaks_process_chromosome_cpp`, anno_line_id, anno_transcript, anno_region, anno_start, anno_end, anno_strand, anno_gene, gene_name, gene_start, gene_end, peak_start, peak_end, peak_FC, peak_range, peak_transcripts, seed)
}

